#ifndef WIRESHARK_PLUGIN_SRC_PACKET_UDPCL_H_
#define WIRESHARK_PLUGIN_SRC_PACKET_UDPCL_H_

typedef enum {
    UDPCL_CTRL_XFER_ID = 0x01,
    UDPCL_CTRL_XFER_LEN = 0x02,
    UDPCL_CTRL_XFER_FRAG_OFFSET = 0x03,
    UDPCL_CTRL_XFER_FRAG_DATA = 0x04,
} UdpclControlType;

#endif /* WIRESHARK_PLUGIN_SRC_PACKET_UDPCL_H_ */
